apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    name: apache
  name: apachetest
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'apachetest:1'
  source:
    dockerfile: "FROM centos:7\nRUN yum install -y httpd" 
    git:
      ref: master
      uri: 'git://github.com/laurencio-galicia/Apachetest.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'centos:7'
    type: Docker
  triggers: []
status:
  lastVersion: 0
